# ==============================================================================
# CDISC SDTM Demographics Domain Code Generator
# ==============================================================================
#
# File: emit_demographics_oak_from_spec.R
# Purpose: Dynamically generate R code for mapping CDASH raw data to SDTM
#          Demographics (DM) domain using sdtm.oak package
#
# Input:
#   - CDISC Collection Specializations Excel file
#   - Raw CDASH CSV data file
#   - Study controlled terminology CSV file
#
# Output:
#   - R script for SDTM Demographics domain mapping
#   - Generated SDTM dataset CSV file
#
# Author: Auto-generated by CDISC 360I SDTM Oak Code Generator
# Version: 1.0
# Date: $(date)
#
# Dependencies: sdtm.oak, dplyr, readxl
# ==============================================================================

# Load required packages with error handling
tryCatch({
  if (!requireNamespace("readxl", quietly = TRUE)) {
    stop("Required package 'readxl' is not installed. Please run: install.packages('readxl')")
  }
  if (!requireNamespace("dplyr", quietly = TRUE)) {
    stop("Required package 'dplyr' is not installed. Please run: install.packages('dplyr')")
  }
}, error = function(e) {
  cat("ERROR: Package dependency check failed\n")
  cat("Details:", e$message, "\n")
  stop(e)
})

#' Generate SDTM Demographics Domain Mapping Code
#'
#' @description
#' Dynamically generates R code for mapping CDASH raw data to SDTM Demographics domain
#' using the sdtm.oak package. The function reads CDISC Collection Specializations,
#' raw data structure, and controlled terminology to produce optimized mapping code.
#'
#' @param spec_path Character. Path to CDISC Collection Specializations Excel file
#' @param raw_csv_path Character. Path to raw CDASH CSV data file
#' @param ct_csv_path Character. Path to study controlled terminology CSV file
#' @param domain Character. Target SDTM domain code (default: "DM")
#' @param out_r_path Character. Output path for generated R script (optional)
#'
#' @return Character vector containing the generated R code lines
#'
#' @examples
#' \dontrun{
#' # Generate DM domain mapping code
#' code_lines <- emit_demographics_oak_from_spec(
#'   spec_path = "cdisc_collection_dataset_specializations_draft.xlsx",
#'   raw_csv_path = "DM.csv",
#'   ct_csv_path = "study_ct.csv",
#'   domain = "DM",
#'   out_r_path = "new dm code.R"
#' )
#' }
#'
#' @export
emit_demographics_oak_from_spec <- function(spec_path, raw_csv_path, ct_csv_path, domain = "DM", out_r_path = NULL) {

  # Input validation and logging
  cat("=== CDISC SDTM Demographics Code Generator ===\n")
  cat("Starting code generation for domain:", domain, "\n")
  cat("Timestamp:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n\n")

  # Validate input parameters
  if (!is.character(spec_path) || length(spec_path) != 1) {
    stop("ERROR: spec_path must be a single character string")
  }
  if (!is.character(raw_csv_path) || length(raw_csv_path) != 1) {
    stop("ERROR: raw_csv_path must be a single character string")
  }
  if (!is.character(ct_csv_path) || length(ct_csv_path) != 1) {
    stop("ERROR: ct_csv_path must be a single character string")
  }
  if (!is.character(domain) || length(domain) != 1) {
    stop("ERROR: domain must be a single character string")
  }

  # Validate file existence
  if (!file.exists(spec_path)) {
    stop("ERROR: Specification file not found: ", spec_path)
  }
  if (!file.exists(raw_csv_path)) {
    stop("ERROR: Raw data file not found: ", raw_csv_path)
  }
  if (!file.exists(ct_csv_path)) {
    stop("ERROR: Controlled terminology file not found: ", ct_csv_path)
  }

  cat("✓ Input validation passed\n")

  # Read and validate input files
  tryCatch({
    cat("Reading specification file...\n")
    spec <- readxl::read_excel(spec_path, sheet = "Collection Specializations")

    cat("Reading raw data file...\n")
    raw <- utils::read.csv(raw_csv_path, stringsAsFactors = FALSE)

    cat("Reading controlled terminology file...\n")
    ct_test <- utils::read.csv(ct_csv_path, stringsAsFactors = FALSE)

  }, error = function(e) {
    stop("ERROR: Failed to read input files - ", e$message)
  })

  # Domain-specific processing
  dom <- toupper(domain)
  dom_spec <- subset(spec, toupper(domain) == dom)
  raw_cols <- names(raw)

  cat("✓ Successfully loaded input files\n")
  cat("Domain:", dom, "\n")
  cat("Raw data columns:", length(raw_cols), "\n")
  cat("Domain specification rows:", nrow(dom_spec), "\n")
  cat("Subject count:", nrow(raw), "\n\n")

  # Helper Functions ----

  #' Get codelist for a specific variable from specification
  #' @param var_name Character. SDTM variable name
  #' @return Character. Codelist identifier
  codelist_for <- function(var_name) {
    df <- dom_spec[toupper(dom_spec$variable_name) == toupper(var_name), , drop = FALSE]
    cl <- unique(na.omit(as.character(df$codelist)))
    if (length(cl)) {
      cl[[1]]
    } else {
      # Default codelists for common DM variables
      var_key <- toupper(var_name)
      if (var_key == "SEX") "C66731"          # Sex
      else if (var_key == "RACE") "C74457"    # Race
      else if (var_key == "ETHNIC") "C66790"  # Ethnicity
      else if (var_key == "COUNTRY") "C66728" # Country
      else if (var_key == "AGEU") "C66781"    # Age Units
      else ""
    }
  }

  #' Find raw variable name for an SDTM variable
  #' @param sdtm_var Character. SDTM variable name
  #' @return Character. Raw variable name or NULL if not found
  find_raw_var <- function(sdtm_var) {
    # Look in domain specification first
    df <- dom_spec[toupper(dom_spec$variable_name) == toupper(sdtm_var), , drop = FALSE]
    if (nrow(df) > 0 && any(nzchar(df$raw_variable))) {
      return(as.character(df$raw_variable[which(nzchar(df$raw_variable))[1]]))
    }

    # Check if the variable exists directly in raw data
    if (sdtm_var %in% raw_cols) {
      return(sdtm_var)
    }

    # Common patterns for DM domain
    patterns <- switch(toupper(sdtm_var),
      "AGE" = c("AGE", "DMDTC_AGE", "BIRTH_AGE"),
      "AGEU" = c("AGEU", "AGE_UNIT", "AGE_UNITS"),
      "SEX" = c("SEX", "GENDER"),
      "RACE" = c("RACE", "DMRACE"),
      "ETHNIC" = c("ETHNIC", "ETHNICITY", "DMETHNIC"),
      "COUNTRY" = c("COUNTRY", "DMCOUNTRY"),
      "BRTHDTC" = c("BRTHDTC", "BIRTHDT", "BIRTH_DATE", "DOB"),
      "DMDTC" = c("DMDAT", "DM_DAT", "ENROLL_DATE", "DEMOG_DATE"),
      "RFSTDTC" = c("RFSTDTC", "RFSTDAT", "FIRST_DOSE", "START_DATE"),
      "RFENDTC" = c("RFENDTC", "RFENDAT", "LAST_DOSE", "END_DATE"),
      "SITEID" = c("SITEID", "SITE_ID", "SITE"),
      "INVID" = c("INVID", "INVESTIGATOR_ID", "PINVID"),
      "INVNAM" = c("INVNAM", "INVESTIGATOR_NAME", "PINVNAM"),
      "ARM" = c("ARM", "ARMCD", "TRT_ARM"),
      "ACTARM" = c("ACTARM", "ACTUAL_ARM", "ACT_ARM"),
      NULL
    )

    if (!is.null(patterns)) {
      found <- patterns[patterns %in% raw_cols]
      if (length(found) > 0) return(found[1])
    }

    NULL
  }

  # Code Generation ----
  cat("\nGenerating R code...\n")

  L <- character()

  # Generate file header with metadata
  header_line <- paste("#", paste(rep("=", 76), collapse = ""))
  L <- c(L, header_line)
  L <- c(L, sprintf("# Auto-generated SDTM %s Domain Mapping Code", dom))
  L <- c(L, header_line)
  L <- c(L, "#")
  L <- c(L, sprintf("# Generated by: CDISC 360I SDTM Oak Code Generator"))
  L <- c(L, sprintf("# Generated on: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S")))
  L <- c(L, sprintf("# Domain: %s", dom))
  L <- c(L, sprintf("# Source files:"))
  L <- c(L, sprintf("#   - Specification: %s", basename(spec_path)))
  L <- c(L, sprintf("#   - Raw data: %s", basename(raw_csv_path)))
  L <- c(L, sprintf("#   - Controlled terminology: %s", basename(ct_csv_path)))
  L <- c(L, "#")
  L <- c(L, "# Dependencies: sdtm.oak, dplyr")
  L <- c(L, header_line)
  L <- c(L, "")

  # Load required libraries
  L <- c(L, "# Load required libraries")
  L <- c(L, "library(sdtm.oak)")
  L <- c(L, "library(dplyr)")
  L <- c(L, "")

  # Data loading and preparation
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# Data Loading and Preparation")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "")
  L <- c(L, "# Load raw CDASH data")
  L <- c(L, sprintf("%s_raw <- read.csv('%s', stringsAsFactors = FALSE)", tolower(dom), raw_csv_path))
  L <- c(L, "")
  L <- c(L, "# Load study controlled terminology")
  L <- c(L, sprintf("study_ct <- read.csv('%s', stringsAsFactors = FALSE)", ct_csv_path))
  L <- c(L, "")
  L <- c(L, "# Generate oak ID variables for data tracking")
  subj_candidates <- c("USUBJID","SUBJID","PATNUM","PATID","SUBJECT")
  pat_var <- subj_candidates[subj_candidates %in% raw_cols][1]
  if (is.na(pat_var)) pat_var <- "SUBJID"
  L <- c(L, sprintf("%s_raw <- %s_raw %%>%%", tolower(dom), tolower(dom)))
  L <- c(L, sprintf("  generate_oak_id_vars("))
  L <- c(L, sprintf("    pat_var = '%s',", pat_var))
  L <- c(L, sprintf("    raw_src = '%s'", dom))
  L <- c(L, "  )")
  L <- c(L, "")
  L <- c(L, "# Set up ID variables for sdtm.oak functions")
  L <- c(L, "id_vars <- oak_id_vars()")
  L <- c(L, "")

  # Generate demographics mapping
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# Demographics Variable Mappings")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "#")
  L <- c(L, "# Map CDASH demographics variables to SDTM DM domain variables")
  L <- c(L, "# DM is a special domain with one record per subject")
  L <- c(L, "#")
  L <- c(L, "")

  L <- c(L, sprintf("%s <- %s_raw %%>%%", dom, tolower(dom)))
  L <- c(L, "")

  # Map age
  age_var <- find_raw_var("AGE")
  if (!is.null(age_var)) {
    L <- c(L, "  # Map AGE (Age)")
    L <- c(L, "  assign_no_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", age_var),
           "    tgt_var = 'AGE',",
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
  }

  # Map age units
  ageu_var <- find_raw_var("AGEU")
  if (!is.null(ageu_var)) {
    ageu_cl <- codelist_for("AGEU")
    L <- c(L, "  # Map AGEU (Age Units)")
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", ageu_var),
           "    tgt_var = 'AGEU',",
           "    ct_spec = study_ct,",
           sprintf("    ct_clst = '%s',", ageu_cl),
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
  }

  # Map sex
  sex_var <- find_raw_var("SEX")
  if (!is.null(sex_var)) {
    sex_cl <- codelist_for("SEX")
    L <- c(L, "  # Map SEX (Sex)")
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", sex_var),
           "    tgt_var = 'SEX',",
           "    ct_spec = study_ct,",
           sprintf("    ct_clst = '%s',", sex_cl),
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
  }

  # Map race
  race_var <- find_raw_var("RACE")
  if (!is.null(race_var)) {
    race_cl <- codelist_for("RACE")
    L <- c(L, "  # Map RACE (Race)")
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", race_var),
           "    tgt_var = 'RACE',",
           "    ct_spec = study_ct,",
           sprintf("    ct_clst = '%s',", race_cl),
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
  }

  # Map ethnicity
  ethnic_var <- find_raw_var("ETHNIC")
  if (!is.null(ethnic_var)) {
    ethnic_cl <- codelist_for("ETHNIC")
    L <- c(L, "  # Map ETHNIC (Ethnicity)")
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", ethnic_var),
           "    tgt_var = 'ETHNIC',",
           "    ct_spec = study_ct,",
           sprintf("    ct_clst = '%s',", ethnic_cl),
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
  }

  # Map country
  country_var <- find_raw_var("COUNTRY")
  if (!is.null(country_var)) {
    country_cl <- codelist_for("COUNTRY")
    L <- c(L, "  # Map COUNTRY (Country)")
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", country_var),
           "    tgt_var = 'COUNTRY',",
           "    ct_spec = study_ct,",
           sprintf("    ct_clst = '%s',", country_cl),
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
  }

  # Map demographics collection date
  dmdt_var <- find_raw_var("DMDTC")
  if (!is.null(dmdt_var)) {
    L <- c(L, "  # Map DMDTC (Date/Time of Demographics Collection)")
    L <- c(L, "  assign_datetime(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", dmdt_var),
           "    tgt_var = 'DMDTC',",
           "    raw_fmt = c('dd-mmm-yyyy', 'dd-MMM-yyyy')",
           "  ) %>%")
    L <- c(L, "")
  }

  # Map site ID
  site_var <- find_raw_var("SITEID")
  if (!is.null(site_var)) {
    L <- c(L, "  # Map SITEID (Study Site Identifier)")
    L <- c(L, "  assign_no_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", site_var),
           "    tgt_var = 'SITEID',",
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
  }

  # Remove the trailing %>% from the last line if it exists
  if (length(L) > 0 && grepl("  \\) %>%$", L[length(L)])) {
    L[length(L)] <- gsub(" %>%$", "", L[length(L)])
  }

  L <- c(L, "")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# SDTM Derived Variables")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "#")
  L <- c(L, "# Create derived variables required for SDTM compliance")
  L <- c(L, "# - STUDYID, DOMAIN, USUBJID: Study and subject identifiers")
  L <- c(L, "# - Reference dates: RFSTDTC, RFENDTC")
  L <- c(L, "# - Treatment arms: ARM, ACTARM")
  L <- c(L, "#")
  L <- c(L, "")

  L <- c(L, sprintf("%s <- %s %%>%%", dom, dom))
  L <- c(L, "  dplyr::mutate(",
         sprintf("    DOMAIN = '%s',", dom),
         sprintf("    # Get STUDYID from %s_raw using oak_id matching", tolower(dom)),
         sprintf("    STUDYID = %s_raw$STUDYID[match(oak_id, %s_raw$oak_id)],", tolower(dom), tolower(dom)),
         "    # Create USUBJID by combining STUDYID and patient_number (from oak_id_vars)",
         "    USUBJID = paste0(.data$STUDYID, '-', .data$patient_number),",
         "    # Reference start date (typically first exposure)",
         "    # TODO: Map from actual study reference dates",
         "    RFSTDTC = NA_character_,",
         "    # Reference end date (typically last exposure or follow-up)",
         "    RFENDTC = NA_character_,",
         "    # Planned treatment arm",
         "    ARM = NA_character_,",
         "    # Actual treatment arm",
         "    ACTARM = NA_character_,",
         "    # Randomization date",
         "    RFXSTDTC = NA_character_,",
         "    # End of participation date",
         "    RFXENDTC = NA_character_",
         "  )")
  L <- c(L, "")

  # Final variable selection - keep only SDTM variables
  L <- c(L, "  # Select final SDTM variables")
  final_vars <- c("STUDYID", "DOMAIN", "USUBJID", "SUBJID", "SITEID",
                  "AGE", "AGEU", "SEX", "RACE", "ETHNIC", "COUNTRY",
                  "DMDTC", "BRTHDTC", "DTHDTC", "DTHFL",
                  "RFSTDTC", "RFENDTC", "RFXSTDTC", "RFXENDTC", "RFICDTC", "RFPENDTC",
                  "ARM", "ARMCD", "ACTARM", "ACTARMCD",
                  "RANDDT", "RANDTC", "DMDTDIS", "DSTERM", "DSDECOD",
                  "INVID", "INVNAM", "DMDY")
  final_vars_str <- paste0("'", final_vars, "'", collapse = ", ")
  L <- c(L, sprintf("  dplyr::select(dplyr::any_of(c(%s)))", final_vars_str))
  L <- c(L, "")
  L <- c(L, "")
  L <- c(L, paste("#", paste(rep("-", 48), collapse = "")))
  L <- c(L, "# Save Results")
  L <- c(L, paste("#", paste(rep("-", 48), collapse = "")))
  L <- c(L, "")
  L <- c(L, "# Save as CSV")
  L <- c(L, sprintf("write.csv(%s, '%s_from_sdtm_oak_codegen.csv', row.names = FALSE)", dom, dom))
  L <- c(L, sprintf("cat('✓ SDTM %s dataset CSV created: %s_from_sdtm_oak_codegen.csv\\n')", dom, dom))
  L <- c(L, "")
  L <- c(L, "# Save as XPT format")
  L <- c(L, "if (requireNamespace('haven', quietly = TRUE)) {")
  L <- c(L, sprintf("  haven::write_xpt(%s, '%s_from_sdtm_oak_codegen.xpt')", dom, dom))
  L <- c(L, sprintf("  cat('✓ SDTM %s dataset XPT created: %s_from_sdtm_oak_codegen.xpt\\n')", dom, dom))
  L <- c(L, "} else {")
  L <- c(L, "  cat('⚠ haven package not available - XPT export skipped\\n')")
  L <- c(L, "  cat('  Install with: install.packages(\"haven\")\\n')")
  L <- c(L, "}")
  L <- c(L, "")
  L <- c(L, sprintf("cat('Dataset dimensions:', nrow(%s), 'rows x', ncol(%s), 'columns\\n')", dom, dom))

  # Write output file if specified
  if (!is.null(out_r_path)) {
    tryCatch({
      writeLines(L, out_r_path)
      cat("✓ Generated R code saved to:", out_r_path, "\n")
    }, error = function(e) {
      warning("Failed to write output file: ", e$message)
    })
  }

  # Final validation and summary
  cat("\n=== Code Generation Complete ===\n")
  cat("Generated code lines:", length(L), "\n")
  cat("Domain:", dom, "\n")
  cat("Subject count:", nrow(raw), "\n")
  cat("Timestamp:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")
  cat("=====================================\n\n")

  invisible(L)
}

# Example usage for DM domain
emit_demographics_oak_from_spec("cdisc_collection_dataset_specializations_draft.xlsx",
                                 "DM.csv",
                                 "study_ct.csv",
                                 domain = "DM",
                                 out_r_path = "new dm code.R")