# ============================================================================
# Auto-generated SDTM DM Domain Mapping Code
# ============================================================================
#
# Generated by: CDISC 360I SDTM Oak Code Generator
# Generated on: 2025-09-28 22:13:40
# Domain: DM
# Source files:
#   - Specification: cdisc_collection_dataset_specializations_draft.xlsx
#   - Raw data: DM.csv
#   - Controlled terminology: study_ct.csv
#
# Dependencies: sdtm.oak, dplyr
# ============================================================================

# Load required libraries
library(sdtm.oak)
library(dplyr)

# ==============================================================================
# Data Loading and Preparation
# ==============================================================================

# Load raw CDASH data
dm_raw <- read.csv('DM.csv', stringsAsFactors = FALSE)

# Load study controlled terminology
study_ct <- read.csv('study_ct.csv', stringsAsFactors = FALSE)

# Generate oak ID variables for data tracking
dm_raw <- dm_raw %>%
  generate_oak_id_vars(
    pat_var = 'SUBJID',
    raw_src = 'DM'
  )

# Set up ID variables for sdtm.oak functions
id_vars <- oak_id_vars()

# ==============================================================================
# Demographics Variable Mappings
# ==============================================================================
#
# Map CDASH demographics variables to SDTM DM domain variables
# DM is a special domain with one record per subject
#

DM <- dm_raw %>%

  # Map AGE (Age)
  assign_no_ct(
    raw_dat = dm_raw,
    raw_var = 'AGE',
    tgt_var = 'AGE',
    id_vars = id_vars
  ) %>%

  # Map AGEU (Age Units)
  assign_ct(
    raw_dat = dm_raw,
    raw_var = 'AGEU',
    tgt_var = 'AGEU',
    ct_spec = study_ct,
    ct_clst = 'C66781',
    id_vars = id_vars
  ) %>%

  # Map SEX (Sex)
  assign_ct(
    raw_dat = dm_raw,
    raw_var = 'SEX',
    tgt_var = 'SEX',
    ct_spec = study_ct,
    ct_clst = 'C66731',
    id_vars = id_vars
  ) %>%

  # Map RACE (Race)
  assign_ct(
    raw_dat = dm_raw,
    raw_var = 'RACE',
    tgt_var = 'RACE',
    ct_spec = study_ct,
    ct_clst = 'C74457',
    id_vars = id_vars
  ) %>%

  # Map ETHNIC (Ethnicity)
  assign_ct(
    raw_dat = dm_raw,
    raw_var = 'ETHNIC',
    tgt_var = 'ETHNIC',
    ct_spec = study_ct,
    ct_clst = 'C66790',
    id_vars = id_vars
  ) %>%

  # Map COUNTRY (Country)
  assign_ct(
    raw_dat = dm_raw,
    raw_var = 'COUNTRY',
    tgt_var = 'COUNTRY',
    ct_spec = study_ct,
    ct_clst = 'C66728',
    id_vars = id_vars
  ) %>%

  # Map DMDTC (Date/Time of Demographics Collection)
  assign_datetime(
    raw_dat = dm_raw,
    raw_var = 'DMDAT',
    tgt_var = 'DMDTC',
    raw_fmt = c('dd-mmm-yyyy', 'dd-MMM-yyyy')
  ) %>%

  # Map SITEID (Study Site Identifier)
  assign_no_ct(
    raw_dat = dm_raw,
    raw_var = 'SITEID',
    tgt_var = 'SITEID',
    id_vars = id_vars
  ) %>%


# ==============================================================================
# SDTM Derived Variables
# ==============================================================================
#
# Create derived variables required for SDTM compliance
# - STUDYID, DOMAIN, USUBJID: Study and subject identifiers
# - Reference dates: RFSTDTC, RFENDTC
# - Treatment arms: ARM, ACTARM
#

DM <- DM %>%
  dplyr::mutate(
    DOMAIN = 'DM',
    # Get STUDYID from dm_raw using oak_id matching
    STUDYID = dm_raw$STUDYID[match(oak_id, dm_raw$oak_id)],
    # Create USUBJID by combining STUDYID and patient_number (from oak_id_vars)
    USUBJID = paste0(.data$STUDYID, '-', .data$patient_number),
    # Reference start date (typically first exposure)
    # TODO: Map from actual study reference dates
    RFSTDTC = NA_character_,
    # Reference end date (typically last exposure or follow-up)
    RFENDTC = NA_character_,
    # Planned treatment arm
    ARM = NA_character_,
    # Actual treatment arm
    ACTARM = NA_character_,
    # Randomization date
    RFXSTDTC = NA_character_,
    # End of participation date
    RFXENDTC = NA_character_
  )

  # Select final SDTM variables
  dplyr::select(dplyr::any_of(c('STUDYID', 'DOMAIN', 'USUBJID', 'SUBJID', 'SITEID', 'AGE', 'AGEU', 'SEX', 'RACE', 'ETHNIC', 'COUNTRY', 'DMDTC', 'BRTHDTC', 'DTHDTC', 'DTHFL', 'RFSTDTC', 'RFENDTC', 'RFXSTDTC', 'RFXENDTC', 'RFICDTC', 'RFPENDTC', 'ARM', 'ARMCD', 'ACTARM', 'ACTARMCD', 'RANDDT', 'RANDTC', 'DMDTDIS', 'DSTERM', 'DSDECOD', 'INVID', 'INVNAM', 'DMDY')))


# ------------------------------------------------
# Save Results
# ------------------------------------------------

# Save as CSV
write.csv(DM, 'DM_from_sdtm_oak_codegen.csv', row.names = FALSE)
cat('✓ SDTM DM dataset CSV created: DM_from_sdtm_oak_codegen.csv\n')

# Save as XPT format
if (requireNamespace('haven', quietly = TRUE)) {
  haven::write_xpt(DM, 'DM_from_sdtm_oak_codegen.xpt')
  cat('✓ SDTM DM dataset XPT created: DM_from_sdtm_oak_codegen.xpt\n')
} else {
  cat('⚠ haven package not available - XPT export skipped\n')
  cat('  Install with: install.packages("haven")\n')
}

cat('Dataset dimensions:', nrow(DM), 'rows x', ncol(DM), 'columns\n')
