# ============================================================================
# Auto-generated SDTM AE Domain Mapping Code
# ============================================================================
#
# Generated by: CDISC 360I SDTM Oak Code Generator
# Generated on: 2025-09-28 21:06:17
# Domain: AE
# Source files:
#   - Specification: cdisc_collection_dataset_specializations_draft.xlsx
#   - Raw data: AE.csv
#   - Controlled terminology: study_ct.csv
#
# Dependencies: sdtm.oak, dplyr
# ============================================================================

# Load required libraries
library(sdtm.oak)
library(dplyr)

# ==============================================================================
# Data Loading and Preparation
# ==============================================================================

# Load raw CDASH data
ae_raw <- read.csv('AE.csv', stringsAsFactors = FALSE)

# Load study controlled terminology
study_ct <- read.csv('study_ct.csv', stringsAsFactors = FALSE)

# Generate oak ID variables for data tracking
ae_raw <- ae_raw %>%
  generate_oak_id_vars(
    pat_var = 'SUBJID',
    raw_src = 'AE'
  )

# Set up ID variables for sdtm.oak functions
id_vars <- oak_id_vars()

# ==============================================================================
# Event Variable Mappings
# ==============================================================================
#
# Map CDASH adverse event variables to SDTM AE domain variables
#

AE <- ae_raw %>%

  # Map AETERM (Reported Term for the Adverse Event)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AETERM',
    tgt_var = 'AETERM',
    id_vars = id_vars
  ) %>%

  # Map AEDECOD (Dictionary-Derived Term)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEDECOD',
    tgt_var = 'AEDECOD',
    id_vars = id_vars
  ) %>%

  # Map AEBODSYS (Body System or Organ Class) from AESOC
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AESOC',
    tgt_var = 'AEBODSYS',
    id_vars = id_vars
  ) %>%

  # Map AELLT (Lowest Level Term)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AELLT',
    tgt_var = 'AELLT',
    id_vars = id_vars
  ) %>%

  # Map AELLTCD (Lowest Level Term Code)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AELLTCD',
    tgt_var = 'AELLTCD',
    id_vars = id_vars
  ) %>%

  # Map AEHLT (High Level Term)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEHLT',
    tgt_var = 'AEHLT',
    id_vars = id_vars
  ) %>%

  # Map AEHLTCD (High Level Term Code)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEHLTCD',
    tgt_var = 'AEHLTCD',
    id_vars = id_vars
  ) %>%

  # Map AEHLGT (High Level Group Term)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEHLGT',
    tgt_var = 'AEHLGT',
    id_vars = id_vars
  ) %>%

  # Map AEHLGTCD (High Level Group Term Code)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEHLGTCD',
    tgt_var = 'AEHLGTCD',
    id_vars = id_vars
  ) %>%

  # Map AESOCCD (System Organ Class Code)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AESOCCD',
    tgt_var = 'AESOCCD',
    id_vars = id_vars
  ) %>%

  # Map AEPTCD (Preferred Term Code)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEPTCD',
    tgt_var = 'AEPTCD',
    id_vars = id_vars
  ) %>%

  # Map AESEV (Severity/Intensity) - convert numeric to text
  dplyr::mutate(
    AESEV_TEMP = ae_raw$AESEV[match(oak_id, ae_raw$oak_id)],
    AESEV = dplyr::case_when(
      AESEV_TEMP == '1' ~ 'MILD',
      AESEV_TEMP == '2' ~ 'MODERATE',
      AESEV_TEMP == '3' ~ 'SEVERE',
      TRUE ~ as.character(AESEV_TEMP)
    )
  ) %>%
  dplyr::select(-AESEV_TEMP) %>%

  # Map AESER (Serious Event)
  assign_ct(
    raw_dat = ae_raw,
    raw_var = 'AESER',
    tgt_var = 'AESER',
    ct_spec = study_ct,
    ct_clst = 'C66742',
    id_vars = id_vars
  ) %>%

  # Map AEREL (Causality Assessment)
  assign_ct(
    raw_dat = ae_raw,
    raw_var = 'AEREL',
    tgt_var = 'AEREL',
    ct_spec = study_ct,
    ct_clst = 'C66742',
    id_vars = id_vars
  ) %>%

  # Map AEACN (Action Taken with Regard to Treatment)
  assign_ct(
    raw_dat = ae_raw,
    raw_var = 'AEACN',
    tgt_var = 'AEACN',
    ct_spec = study_ct,
    ct_clst = 'C66767',
    id_vars = id_vars
  ) %>%

  # Map AEOUT (Outcome of Adverse Event)
  assign_ct(
    raw_dat = ae_raw,
    raw_var = 'AEOUT',
    tgt_var = 'AEOUT',
    ct_spec = study_ct,
    ct_clst = 'C66768',
    id_vars = id_vars
  ) %>%

  # Map AESTDTC (Start Date/Time of Adverse Event)
  assign_datetime(
    raw_dat = ae_raw,
    raw_var = 'AESTDAT',
    tgt_var = 'AESTDTC',
    raw_fmt = c('dd-mmm-yyyy', 'dd-MMM-yyyy')
  ) %>%

  # Map AEENDTC (End Date/Time of Adverse Event)
  assign_datetime(
    raw_dat = ae_raw,
    raw_var = 'AEENDAT',
    tgt_var = 'AEENDTC',
    raw_fmt = c('dd-mmm-yyyy', 'dd-MMM-yyyy')
  ) %>%

  # Map AEYN (Any Adverse Events?)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEYN',
    tgt_var = 'AEYN',
    id_vars = id_vars
  ) %>%

  # Map AESPID (Sponsor-Defined Identifier)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AESPID',
    tgt_var = 'AESPID',
    id_vars = id_vars
  ) %>%

  # Map AEONGO (Ongoing Adverse Event)
  assign_no_ct(
    raw_dat = ae_raw,
    raw_var = 'AEONGO',
    tgt_var = 'AEONGO',
    id_vars = id_vars
  ) %>%


# ==============================================================================
# SDTM Derived Variables
# ==============================================================================
#
# Create derived variables required for SDTM compliance
# - STUDYID, DOMAIN, USUBJID: Study and subject identifiers
# - AESEQ: Sequence numbers within subject
# - AEDY: Study day of start of adverse event
#

AE <- AE %>%
  dplyr::mutate(
    DOMAIN = 'AE',
    # Get STUDYID from ae_raw using oak_id matching
    STUDYID = ae_raw$STUDYID[match(oak_id, ae_raw$oak_id)],
    # Create USUBJID by combining STUDYID and patient_number (from oak_id_vars)
    USUBJID = paste0(.data$STUDYID, '-', .data$patient_number),
    # Derive AEDY (Study Day of Start of Adverse Event)
    # TODO: Implement study day calculation based on RFSTDTC
    AEDY = NA_integer_
  ) %>%

  # Create sequence numbers within subject
  dplyr::group_by(STUDYID, USUBJID) %>%
  dplyr::mutate(AESEQ = dplyr::row_number()) %>%
  dplyr::ungroup() %>%

  # Select final SDTM variables
  dplyr::select(dplyr::any_of(c('STUDYID', 'DOMAIN', 'USUBJID', 'AESEQ', 'AETERM', 'AEDECOD', 'AEBODSYS', 'AESEV', 'AESER', 'AEREL', 'AEACN', 'AEOUT', 'AESTDTC', 'AEENDTC', 'AEDY', 'VISITNUM', 'VISIT', 'AELLT', 'AELLTCD', 'AEHLT', 'AEHLTCD', 'AEHLGT', 'AEHLGTCD', 'AESOCCD', 'AEPTCD', 'AEYN', 'AESPID', 'AEONGO')))


# ------------------------------------------------
# Save Results
# ------------------------------------------------

# Save as CSV
write.csv(AE, 'AE_from_sdtm_oak_codegen.csv', row.names = FALSE)
cat('✓ SDTM AE dataset CSV created: AE_from_sdtm_oak_codegen.csv\n')

# Save as XPT format
if (requireNamespace('haven', quietly = TRUE)) {
  haven::write_xpt(AE, 'AE_from_sdtm_oak_codegen.xpt')
  cat('✓ SDTM AE dataset XPT created: AE_from_sdtm_oak_codegen.xpt\n')
} else {
  cat('⚠ haven package not available - XPT export skipped\n')
  cat('  Install with: install.packages("haven")\n')
}

cat('Dataset dimensions:', nrow(AE), 'rows x', ncol(AE), 'columns\n')
